# Generated by Django 5.0.6 on 2024-06-08 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_rename_seats_booking_num_tickets_remove_booking_user_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='num_tickets',
            new_name='seats',
        ),
    ]
